### ISSUE TITLE
[Sugestão] Implementar versão para ios como webapp

### ISSUE THREAD

**Issue by daniwenne** [pitroldev/cardapio-mobile-uerj#1]
Como o app é implementado em js, seria possível implementar uma versão como website? Caso seja possível, o app poderia ser adicionado como ícone com a função "Adicionar à tela inicial" do safari para os usuários de ios. As credenciais acesso poderiam ser salvas como cookies.

**Comment by pitroldev** [comment]
Sim, seria completamente possível! Porém atualmente não tenho o tempo hábil para reescrever o aplicativo como PWA :/

Tem alguns pontos de atenção no porte do aplicativo para PWA, entre eles estão:
- Acessibilidade para deficientes visuais
- Custos para hospedagem da aplicação
